services:
  mysql_container:
    image: mysql_image:Dockerfile
    build: 
      context: .
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=docker_db
